- main.tf
- vars.tf
Add two new options to specify excluded regions for AWS integration and tags to filter out EC2 instances.
> Add excluded regions and EC2 filtering

- versions.tf
The recent change (https://github.com/scribd/terraform-aws-datadog/pull/10) requires a very recent datadog provider (2.10.0) which led to my pipeline failure at the `terraform plan` stage.
With this change, we can catch version mismatch at the `terraform init` stage, and makes the version requirement explicit to future users.
Reference: 
1. `excluded_regions` parameter was added in datadog provider version `2.10.0`: https://github.com/terraform-providers/terraform-provider-datadog/blob/master/CHANGELOG.md#2100-june-26-2020
> Add minimum version requirement for terraform and datadog

- logs_monitoring.tf
- vars.tf
This PR adds new `dd_forwarder_dd_site` variable, to allow users to set `DdSite` parameter for datadog forwarder CF stack. Also CF stack version updated (no major changes there)
> feat(log forwarding): support DdSite option + upgrade default CF template version used

- main.tf
To fix following error:
User:
arn:aws:sts::XYZ:assumed-role/datadog-integration-role/vault-app3.eu1.prod.dog-datadog-delancie-crawlerXYZ
is not authorized to perform: cloudtrail:LookupEvents
> Add cloudtrail:LookupEvents IAM rights

- versions.tf
#20 
I know there is this other PR that updates all the github actions to run using terraform version 0.13 but it has been open for a while: https://github.com/scribd/terraform-aws-datadog/pull/15
This is a simple fix that just allows us to use terraform version 0.13 with this module.
> fix: make 0.12 minimum terraform cli version requirement so this module works with terraform version 0.13

- versions.tf
Missed this in the previous pull request: https://github.com/scribd/terraform-aws-datadog/pull/21
This is required for terraform version 0.13 to work
Closes #23
> fix: use proper provider source for datadog

- main.tf
I deployed the integration, the plan and apply have been success, however when I checked the integration page in the [Datadog Integrations Page](https://app.datadoghq.eu/account/settings#integrations/amazon-web-services)  I got the following screen:
After adding the cloudwatch:ListMetrics permission to the policy and redeployed the code, the issue has gone.
> Adding cloudwatch:ListMetrics

- vars.tf
change the datadog lambda forwarder version from v3.17.0 to v3.27.0. There are many feature improvements in this version such as the support for SNS topic subscriptions for S3 bucket events
> feat: changes dd lambda default version from v3.17.0 to v3.27.0

- versions.tf
Updating this module to work with Terraform versions up to, but not including, 1.1.
Tested this using both 0.15.3 and 1.0.2 deployments, both worked as expected.
> feat: enable support for Terraform 1.0

- main.tf
Added `states:DescribeStateMachine` permission to the `aws_iam_policy` of `datadog-core`. This is a core step of [integrating with AWS Step Functions](https://docs.datadoghq.com/integrations/amazon_step_functions/).
Tested on forked branch and works as expected.
> feat: added states permissions to IAM policy

- versions.tf
Updating this module to work with Terraform versions up to, but not including, 1.3.0.
> feat: enable support for Terraform 1.1.3

- .github/workflows/terraform_and_release.yml
fixes https://github.com/scribd/terraform-aws-datadog/issues/41
Somewhere along the way, the plugins below had a dependency requirement of semantic_release >=18:
```
npm WARN @semantic-release/git@10.0.1 requires a peer of semantic-release@>=18.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/changelog@6.0.1 requires a peer of semantic-release@>=18.0.0 but none is installed. You must install peer dependencies yourself.
```
This PR pins the versions of sementic-release at the current release level.
> fix: explicitly specify the versions for semantic-release

- versions.tf
v4 of the AWS provider introduced some breaking changes. We need to: 
This PR addresses the former requirement. 
relates to https://github.com/scribd/terraform-aws-datadog/issues/43
> fix: restrict aws provider to <4 for this major branch

- README.md
- logs_monitoring_elb.tf
- versions.tf
This should fix https://github.com/scribd/terraform-aws-datadog/issues/43
**BREAKING CHANGE**
Based on the below understanding , I think we do not need to do manual import in most of the cases. However we should create a major version though. 
Each of the new aws_s3_bucket_* resources relies on S3 API calls that utilize a PUT action in order to modify the target S3 bucket. Because these API calls adhere to standard HTTP methods for REST APIs, they should handle situations where the target configuration already exists (as noted in the [HTTP RFC](https://datatracker.ietf.org/doc/html/rfc2616#section-9.6)). Given that this is the case, it's not strictly necessary to import any new aws_s3_bucket_* resources that are a one-to-one translation from previous versions of the AWS provider -- on the …
> feat!: enable support for aws provider 4.0+

- versions.tf
Using Terraform 1.3.2, this module seems to work just as expected, all resources created fine. I can see no breaking changes between tf 1.2 and 1.3 which should affect this. This will relax the requirements to allow any 1.3.x to be used.
> feat: enable support for Terraform 1.3.x

- logs_monitoring_elb.tf
Remove private ACL terraform resource. 
Broken since April, 2023 for creating new S3 buckets and specifying ACL's: 
https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/
> Remove private ACL S3 terraform resource

- logs_monitoring_cloudwatch_log.tf
While typical statement_id is generated by terraform -- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission.html
if log-groups are too lengthy, this will cause issue where `statement_id` is more than 100 characters, refer - https://docs.aws.amazon.com/lambda/latest/dg/API_AddPermission.html#API_AddPermission_RequestSyntax
> Fix `statement_id` length

- logs_monitoring_cloudwatch_log.tf
In case `var.cloudwatch_log_groups` changes somewhere in the middle of the list, all resources indexed since that position must be recreated. 
This can be remedied by switching to `for_each` instead of `count`
Was:
```
+ resource "aws_cloudwatch_log_subscription_filter" "test_lambdafunction_logfilter" {
+ destination_arn = (known after apply)
+ distribution    = "Random"
+ id              = (known after apply)
+ log_group_name  = "/aws/sagemaker/TransformJobs"
+ name            = "/aws/sagemaker/TransformJobs-filter"
+ role_arn        = (known after apply)
}
+ resource "aws_cloudwatch_log_subscription_filter" "test_lambdafunction_logfilter" {
+ destination_arn = (known after apply)
+ distribution    = "Random"
+ id              = (known after apply)
+ log_group_name  = …
```
> Switch to for_each for log forwarding resources

- locals.tf
- logs_monitoring_cloudwatch_log.tf
- vars.tf
Currently failing with
```
│ Error: adding Lambda Permission (arn:aws:lambda:us-east-2:591234544403:function:model-inference-development-datadog-forwarder/_aws_sagemaker_Endpoints_recs-ranker-rn-scribd-has-read-after-AllowExecutionFromCloudWatchLogs): PolicyLengthExceededException: The final policy size (20782) is bigger than the limit (20480).
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "e220c7fb-c4c9-4b93-9f15-beba592a3afc"
│   },
│   Message_: "The final policy size (20782) is bigger than the limit (20480).",
│   Type: "User"
│ }
│
│   with module.datadog[0].aws_lambda_permission.allow_cloudwatch_logs_to_call_dd_lambda_handler["/aws/sagemaker/Endpoints/recs-ranker-rn-scribd-has-read-after"],
│   on .terraform/modules/datadog/logs_monitoring_cloudwatch_log.tf line …
```
> fix: Work around the limit in lambda policy size

- logs_monitoring.tf
- logs_monitoring_elb.tf
- main.tf
- vars.tf
This should fix https://github.com/scribd/terraform-aws-datadog/issues/4
> fix!:added additional variables for tags
